# Depends on docker-compose.yml.
version: '3'

services:
  datadog:
    image: datadog/agent:6-py2
    container_name: tsorage-datadog
    environment:
      #DD_API_KEY: "4b8639ed-0e90-4b3f-8a45-e87c22d17887"
      DD_API_KEY: "6bd66ef491424668aa0175e6ad1b2a99"
      DD_SITE: datadoghq.eu
      DD_DD_URL: http://ingestion:8080
    depends_on:
      - cassandra-init
      - ingestion
      - processor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - container-sync:/sync
    command: [
      "sh", "-c", "
        rm /etc/ssl/openssl.cnf &&
        apt-get update && apt-get install -y wget &&
        wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh &&
        chmod +x /wait-for-it.sh &&
        ./wait-for-it.sh ingestion:8080 --timeout=600 -- sh -c \"
        while [ ! -f '/sync/db_initialized' ]; do
          sleep 1;
        done;
        /init
      \""
    ]
