version: '3'

networks:
  app-tier:
    driver: bridge

services:
  storage:
    image: cassandra:3.11
    ports:
      - "9042:9042"
    volumes:
      - .:/code
      - logvolume01:/var/log
    networks:
      - app-tier
volumes:
  logvolume01: {}