apiVersion: v1
kind: ConfigMap
metadata:
  namespace: cetic-tsorage-dev
  name: tsorage-ingestion-conf
data:
  TSORAGE_KAFKA_HOST: tsorage-kafka.cetic-tsorage-dev.svc.cluster.local
  TSORAGE_HUB_HOST: http://tsorage-hub.cetic-tsorage-dev.svc.cluster.local
