name: unit-tests

on: [push, pull_request]

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: openjdk@1.12
      - name: Cassandra
        run: docker run --name cassandra --publish 9042:9042 -d cassandra:3.11
      - name: Compile
        run: sbt compile
      - name: Test
        run: sbt test
