name: unit-tests

on: [push, pull_request]

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: openjdk@1.12
      - name: Run Cassandra
        run: |
            mkdir -p share
            wget https://raw.githubusercontent.com/cetic/tsorage-storage/dev/cassandra_prod.cql -O ./share/cassandra.cql
            wget https://raw.githubusercontent.com/cetic/tsorage-storage/dev/test_data.cql -O ./share/test_data.cql
            docker run --name cassandra --publish 9042:9042 -d -v $PWD/share:/share cassandra:3.11
      - name: Compile project
        run: sbt compile
      - name: Initialize Cassandra
        run: |
            # Create database schema.
            docker exec cassandra cqlsh -f /share/cassandra.cql
            # Insert test data.
            docker exec cassandra cqlsh -f /share/test_data.cql
      - name: Run unit tests
        run: sbt test
