name: unit-tests

on: [push, pull_request]

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: openjdk@1.12
      - name: Cassandra
        run: |
            echo "deb http://www.apache.org/dist/cassandra/debian 311x main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
            curl https://www.apache.org/dist/cassandra/KEYS | sudo apt-key add -
            sudo apt-get update
            sudo apt-get install -y cassandra
            cassandra
      - name: Compile
        run: sbt compile
      - name: Test
        run: sbt test
